server:
  port: 8080
  context-path: /hy-web
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:config/mybatis-config.xml
spring:
  rabbitmq: # RabbitMQ配置
    host: 127.0.0.1
    port: 5672
    username: haiyoung
    password: 123
  data: #连接认证mongodb
    mongodb:
      uri: mongodb://root:123456@127.0.0.1:27017/haiyoung
#logging:
#  config: classpath:config/logback-web.xml #logback配置文件
