spring:
  profiles:
    active: dev
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/haiyoung?useSSL=true
    username: root
    password: 891208
  thymeleaf:
    # 这个是配置模板路径的，默认是templates
    prefix: classpath:/templates/
    suffix: .html
    # 模板的模式
    #spring.thymeleaf.mode的默认值是HTML5，其实是一个很严格的检查，改为LEGACYHTML5可以得到一个可能更友好亲切的格式要求。
    mode: LEGACYHTML5
    encoding: UTF-8
    # 这个开发配置为false，避免改了模板还要重启服务器
    cache: false
    content-type: text/html
    enabled: true
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  http:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  devtools:
    livereload:
      enabled: true
